### ISSUE TITLE
Demo problem

### ISSUE THREAD

**Issue by valerio-bozzolan** [springmeyer/arc.js#42]
Hi all!

I was not able to visit the demo in https://

https://springmeyer.github.io/arc.js/

Having said that also in http:// I'm not sure everything is working. Are you aware of that? Thank you so much :)

**Comment by jgravois** [comment]
hi @valerio-bozzolan 👋 

the demo doesn't work using https because the CDN its using isn't available over https

http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js

the demo runs using http, the tiles just aren't loading ex: http://a.tiles.mapbox.com/v3/springmeyer.map-7jkxlsx1/2/1/2.png
![Screen Shot 2022-02-15 at 8 45 02 AM](https://user-images.githubusercontent.com/3011734/154108359-093fb3cd-948e-4548-b0cb-2db9db65558b.png)

to get things ship shape you'll need to swap in a different leaflet CDN and some different tiles.

https://leafletjs.com/examples/quick-start/

**Comment by valerio-bozzolan** [comment]
Uhm. Maybe the OpenStreetMap default tiles are nice enough instead of MapBox. Also I see that upstream they suggest another CDN:

https://leafletjs.com/examples/quick-start/

**Comment by valerio-bozzolan** [comment]
Here we are:

https://unpkg.com/leaflet@0.7.3/dist/leaflet.js

**Comment by valerio-bozzolan** [comment]
What. That CDN has inconsistent content about that version. Having said that we won't have noticed the difference and we can use that version as well, let's file a bug upstream just to notify that.

https://github.com/Leaflet/Leaflet/issues/8004

**Comment by valerio-bozzolan** [comment]
Thanks!
